name: Build Content Editor

on:
  push:
    branches:
      - '**'

# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev build-essential

      - name: Install dependencies
        run: npm install

      - name: Extract commit information
        id: commit_info
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Clone plugins repository
        run: |
          git clone -b release-5.2.0 https://github.com/JeraldJF/sunbird-content-plugins.git plugins
          cd plugins

      - name: Run build script
        run: |
          chmod +x .github/scripts/build.sh
          .github/scripts/build.sh ${{ steps.commit_info.outputs.branch_name }} ${{ steps.commit_info.outputs.commit_hash }}

      - name: Archive artifacts
        run: |
          mkdir generic-editor-artifacts
          cp generic-editor.zip generic-editor-artifacts
          zip -j generic-editor-artifacts.zip:${{ steps.commit_info.outputs.branch_name }} generic-editor-artifacts/*
          echo "{\"artifact_name\": \"generic-editor-artifacts.zip\", \"artifact_version\": \"${{ steps.commit_info.outputs.branch_name }}\", \"node_name\": \"${{ runner.name }}\"}" > metadata.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generic-editor-artifacts
          path: generic-editor-artifacts.zip, metadata.json